### ISSUE TITLE
Add custom style

### ISSUE THREAD

**Issue by TatuLund** [vaadin/skeleton-starter-flow#138]
In the current app starter there is read me file in the folder where custom style html file should be. It would be better to have simple style html file there and use it in main view. 

Idea behind of this feature request is, that it is really commonly asked question and developers to struggle to get it right (i.e. paths, correct annotation, etc.)

**Comment by Legioth** [comment]
I think we originally had something like that in the starter, along with a `PolymerTemplate` class and an the corresponding `.html` file. We removed those at some point because we wanted this starter to be as simple as possible. We instead introduced https://github.com/vaadin/beverage-starter-flow as a starter that uses a bunch of different core features.

**Comment by samie** [comment]
We already made fix to the default spring starter in https://github.com/vaadin/skeleton-starter-flow-spring/issues/126 adding 3 different examples of styling. Same should go here.

**Comment by anasmi** [comment]
Changes were merged in master branch a couple of days ago https://github.com/vaadin/skeleton-starter-flow/pull/274

Closing this ticket due to it
